name: E2E Tests

on:
  push:
    branches:
      - main  

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run cy:run 